[project]
name = "vrc-dekapu"
version = "0.1.0"
description = "クソでっけぇプッシャーゲーム効率化"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyotp>=2.9.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.1",
]
